ReviewConstants = {
  REVIEWS_RECEIVED: "REVIEWS_RECEIVED",
  REVIEW_RECEIVED: "REVIEW_RECEIVED",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW",
  RECEIVE_RANDOM_REVIEWS: "RECEIVE_RANDOM_REVIEWS",
  RECEIVE_USER_REVIEWS: "RECEIVE_USER_REVIEWS"
};

module.exports = ReviewConstants;
