ReviewConstants = {
  REVIEWS_RECEIVED: "REVIEWS_RECEIVED",
  REVIEW_RECEIVED: "REVIEW_RECEIVED",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW"
};

module.exports = ReviewConstants;
