TaggingConstants = {
  TAGGINGS_RECEIVED: "TAGGINGS_RECEIVED",
  TAGGING_RECEIVED: "TAGGING_RECEIVED",
  UPDATE_TAGGING: "UPDATE_TAGGING",
  DELETE_TAGGING: "DELETE_TAGGING"
};

module.exports = TaggingConstants;
